/* Auto-generated from inst/extdata/branding/colors.csv by tools/build_color_picker_tokens.R */
window.COLOR_TOKENS = [
  { category: "Core Surfaces", key: "bg_canvas", value: "#F8FAFC", description: "", variable: "bg_canvas", fundamental_color: "", heatmap_color: "" },
  { category: "Core Surfaces", key: "bg_card", value: "#FFFFFF", description: "", variable: "bg_card", fundamental_color: "", heatmap_color: "" },
  { category: "Core Surfaces", key: "bg_secondary", value: "#F1F5F9", description: "", variable: "bg_secondary", fundamental_color: "", heatmap_color: "" },
  { category: "Core Surfaces", key: "bg_overlay", value: "rgba(255,255,255,0.98)", description: "", variable: "bg_overlay", fundamental_color: "", heatmap_color: "" },
  { category: "Core Surfaces", key: "bg_accent_soft", value: "#F0FDFA", description: "", variable: "bg_accent_soft", fundamental_color: "", heatmap_color: "" },
  { category: "Core Borders", key: "border_light", value: "#F1F5F9", description: "", variable: "border_light", fundamental_color: "", heatmap_color: "" },
  { category: "Core Borders", key: "border_default", value: "#E2E8F0", description: "", variable: "border_default", fundamental_color: "", heatmap_color: "" },
  { category: "Core Borders", key: "border_band", value: "#E5E7EB", description: "", variable: "border_band", fundamental_color: "", heatmap_color: "" },
  { category: "Core Borders", key: "border_dark", value: "#CBD5E1", description: "", variable: "border_dark", fundamental_color: "", heatmap_color: "" },
  { category: "Core Text", key: "text_primary", value: "#0F172A", description: "", variable: "text_primary", fundamental_color: "", heatmap_color: "" },
  { category: "Core Text", key: "text_secondary", value: "#334155", description: "", variable: "text_secondary", fundamental_color: "", heatmap_color: "" },
  { category: "Core Text", key: "text_tertiary", value: "#475569", description: "", variable: "text_tertiary", fundamental_color: "", heatmap_color: "" },
  { category: "Core Text", key: "text_muted", value: "#64748B", description: "", variable: "text_muted", fundamental_color: "", heatmap_color: "" },
  { category: "Core Text", key: "text_faint", value: "#94A3B8", description: "", variable: "text_faint", fundamental_color: "", heatmap_color: "" },
  { category: "Core Text", key: "text_decorative", value: "#CBD5E1", description: "", variable: "text_decorative", fundamental_color: "", heatmap_color: "" },
  { category: "Core Text", key: "text_accent", value: "#0D9488", description: "", variable: "text_accent", fundamental_color: "", heatmap_color: "" },
  { category: "Core Text", key: "text_on_dark", value: "#FFFFFF", description: "", variable: "text_on_dark", fundamental_color: "", heatmap_color: "" },
  { category: "Percentile Zones", key: "percentile_z1_core", value: "#FCD34D", description: "", variable: "percentile_z1_core", fundamental_color: "", heatmap_color: "" },
  { category: "Percentile Zones", key: "percentile_z1_text", value: "#968548", description: "", variable: "percentile_z1_text", fundamental_color: "", heatmap_color: "" },
  { category: "Percentile Zones", key: "percentile_z1_chip", value: "#FFEBC4", description: "", variable: "percentile_z1_chip", fundamental_color: "", heatmap_color: "" },
  { category: "Percentile Zones", key: "percentile_z2_core", value: "#B3D6DA", description: "", variable: "percentile_z2_core", fundamental_color: "", heatmap_color: "" },
  { category: "Percentile Zones", key: "percentile_z2_text", value: "#9DB3B7", description: "", variable: "percentile_z2_text", fundamental_color: "", heatmap_color: "" },
  { category: "Percentile Zones", key: "percentile_z2_chip", value: "#D3FDFF", description: "", variable: "percentile_z2_chip", fundamental_color: "", heatmap_color: "" },
  { category: "Percentile Zones", key: "percentile_z3_core", value: "#0096A7", description: "", variable: "percentile_z3_core", fundamental_color: "", heatmap_color: "" },
  { category: "Percentile Zones", key: "percentile_z3_text", value: "#0096A7", description: "", variable: "percentile_z3_text", fundamental_color: "", heatmap_color: "" },
  { category: "Percentile Zones", key: "percentile_z3_chip", value: "#BBF5FF", description: "", variable: "percentile_z3_chip", fundamental_color: "", heatmap_color: "" },
  { category: "Percentile Zones", key: "percentile_z4_core", value: "#395966", description: "", variable: "percentile_z4_core", fundamental_color: "", heatmap_color: "" },
  { category: "Percentile Zones", key: "percentile_z4_text", value: "#395966", description: "", variable: "percentile_z4_text", fundamental_color: "", heatmap_color: "" },
  { category: "Percentile Zones", key: "percentile_z4_chip", value: "#C8F0F1", description: "", variable: "percentile_z4_chip", fundamental_color: "", heatmap_color: "" },
  { category: "Fundamental Band", key: "band_tick", value: "#0F172A2E", description: "", variable: "band_tick", fundamental_color: "", heatmap_color: "" },
  { category: "Fundamental Band", key: "band_tick_label", value: "#64748B", description: "", variable: "band_tick_label", fundamental_color: "", heatmap_color: "" },
  { category: "Fundamental Band", key: "band_midpoint", value: "#94A3B8", description: "", variable: "band_midpoint", fundamental_color: "", heatmap_color: "" },
  { category: "Fundamental Band", key: "band_marker", value: "#111827", description: "", variable: "band_marker", fundamental_color: "", heatmap_color: "" },
  { category: "Deltas", key: "delta_pos_text", value: "#15803D", description: "", variable: "delta_pos_text", fundamental_color: "", heatmap_color: "" },
  { category: "Deltas", key: "delta_pos_bg", value: "#DCFCE7", description: "", variable: "delta_pos_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Deltas", key: "delta_neg_text", value: "#EB7161", description: "", variable: "delta_neg_text", fundamental_color: "", heatmap_color: "" },
  { category: "Deltas", key: "delta_neg_bg", value: "#FEE2E2", description: "", variable: "delta_neg_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Deltas", key: "delta_neu_text", value: "#64748B", description: "", variable: "delta_neu_text", fundamental_color: "", heatmap_color: "" },
  { category: "Deltas", key: "delta_neu_bg", value: "#F1F5F9", description: "", variable: "delta_neu_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Favorability", key: "favorability_agree", value: "#0096A7", description: "", variable: "favorability_agree", fundamental_color: "", heatmap_color: "" },
  { category: "Favorability", key: "favorability_neutral", value: "#94A3B8", description: "", variable: "favorability_neutral", fundamental_color: "", heatmap_color: "" },
  { category: "Favorability", key: "favorability_disagree", value: "#EB7161", description: "", variable: "favorability_disagree", fundamental_color: "", heatmap_color: "" },
  { category: "Privacy Row", key: "privacy_item_label", value: "#94A3B8", description: "", variable: "privacy_item_label", fundamental_color: "", heatmap_color: "" },
  { category: "Privacy Row", key: "privacy_overlay_bg", value: "rgba(255,255,255,0.85)", description: "", variable: "privacy_overlay_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Privacy Row", key: "privacy_overlay_border", value: "#CBD5E1", description: "", variable: "privacy_overlay_border", fundamental_color: "", heatmap_color: "" },
  { category: "Privacy Row", key: "privacy_overlay_text", value: "#475569", description: "", variable: "privacy_overlay_text", fundamental_color: "", heatmap_color: "" },
  { category: "Privacy Row", key: "privacy_overlay_shadow", value: "rgba(15,23,42,0.06)", description: "", variable: "privacy_overlay_shadow", fundamental_color: "", heatmap_color: "" },
  { category: "Privacy Page", key: "page_privacy_card_bg", value: "rgba(255,255,255,0.98)", description: "", variable: "page_privacy_card_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Privacy Page", key: "page_privacy_card_border", value: "#CBD5E1", description: "", variable: "page_privacy_card_border", fundamental_color: "", heatmap_color: "" },
  { category: "Privacy Page", key: "page_privacy_card_shadow", value: "rgba(15,23,42,0.10)", description: "", variable: "page_privacy_card_shadow", fundamental_color: "", heatmap_color: "" },
  { category: "Privacy Page", key: "page_privacy_icon_color", value: "#0D9488", description: "", variable: "page_privacy_icon_color", fundamental_color: "", heatmap_color: "" },
  { category: "Privacy Page", key: "page_privacy_icon_bg", value: "#F0FDFA", description: "", variable: "page_privacy_icon_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Privacy Page", key: "page_privacy_eyebrow", value: "#64748B", description: "", variable: "page_privacy_eyebrow", fundamental_color: "", heatmap_color: "" },
  { category: "Privacy Page", key: "page_privacy_title", value: "#0F172A", description: "", variable: "page_privacy_title", fundamental_color: "", heatmap_color: "" },
  { category: "Privacy Page", key: "page_privacy_body", value: "#475569", description: "", variable: "page_privacy_body", fundamental_color: "", heatmap_color: "" },
  { category: "Privacy Page", key: "page_privacy_disclaimer", value: "#94A3B8", description: "", variable: "page_privacy_disclaimer", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_shell_bg", value: "#E2E8F0", description: "", variable: "matrix_shell_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_slide_bg", value: "#F8FAFC", description: "", variable: "matrix_slide_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_header_divider", value: "#CBD5E1", description: "", variable: "matrix_header_divider", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_theme_kicker", value: "#475569", description: "", variable: "matrix_theme_kicker", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_title", value: "#0F172A", description: "", variable: "matrix_title", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_subtitle", value: "#64748B", description: "", variable: "matrix_subtitle", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_axis_line", value: "#94A3B8", description: "", variable: "matrix_axis_line", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_axis_text", value: "#64748B", description: "", variable: "matrix_axis_text", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_axis_main", value: "#334155", description: "", variable: "matrix_axis_main", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_plot_bg", value: "#FFFFFF", description: "", variable: "matrix_plot_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_quadrant_tl_bg", value: "#FFF1F2", description: "", variable: "matrix_quadrant_tl_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_quadrant_tl_text", value: "#E11D48", description: "", variable: "matrix_quadrant_tl_text", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_quadrant_tr_bg", value: "#F0FDFA", description: "", variable: "matrix_quadrant_tr_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_quadrant_tr_text", value: "#0F766E", description: "", variable: "matrix_quadrant_tr_text", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_quadrant_bl_bg", value: "#F8FAFC", description: "", variable: "matrix_quadrant_bl_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_quadrant_bl_text", value: "#64748B", description: "", variable: "matrix_quadrant_bl_text", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_quadrant_br_bg", value: "#F1F5F9", description: "", variable: "matrix_quadrant_br_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_quadrant_br_text", value: "#94A3B8", description: "", variable: "matrix_quadrant_br_text", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_quadrant_divider", value: "#CBD5E1", description: "", variable: "matrix_quadrant_divider", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_dot_critical", value: "#E11D48", description: "", variable: "matrix_dot_critical", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_dot_leverage", value: "#0F766E", description: "", variable: "matrix_dot_leverage", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_dot_monitor", value: "#64748B", description: "", variable: "matrix_dot_monitor", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_dot_maintain", value: "#64748B", description: "", variable: "matrix_dot_maintain", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_point_border", value: "#FFFFFF", description: "", variable: "matrix_point_border", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_point_shadow", value: "rgba(0,0,0,0.15)", description: "", variable: "matrix_point_shadow", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_label_bg", value: "#FFFFFF", description: "", variable: "matrix_label_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_label_text", value: "#334155", description: "", variable: "matrix_label_text", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_label_border", value: "#E2E8F0", description: "", variable: "matrix_label_border", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_label_shadow", value: "rgba(0,0,0,0.08)", description: "", variable: "matrix_label_shadow", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_brand_text", value: "#334155", description: "", variable: "matrix_brand_text", fundamental_color: "", heatmap_color: "" },
  { category: "Decision Matrix", key: "matrix_brand_dot", value: "#0EA5E9", description: "", variable: "matrix_brand_dot", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_shell_bg", value: "#E2E8F0", description: "", variable: "enps_shell_bg", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_slide_bg", value: "#F8FAFC", description: "", variable: "enps_slide_bg", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_card_bg", value: "#FFFFFF", description: "", variable: "enps_card_bg", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_card_border", value: "#E2E8F0", description: "", variable: "enps_card_border", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_card_shadow", value: "rgba(15,23,42,0.04)", description: "", variable: "enps_card_shadow", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_title", value: "#0F172A", description: "", variable: "enps_title", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_subtitle", value: "#64748B", description: "", variable: "enps_subtitle", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_score_value", value: "#0F172A", description: "", variable: "enps_score_value", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_score_label", value: "#64748B", description: "", variable: "enps_score_label", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_delta_bg", value: "#DCFCE7", description: "", variable: "enps_delta_bg", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_delta_text", value: "#16A34A", description: "", variable: "enps_delta_text", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_axis_baseline", value: "#334155", description: "", variable: "enps_axis_baseline", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_axis_baseline_label", value: "#94A3B8", description: "", variable: "enps_axis_baseline_label", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_tug_detractor_bg", value: "#E11D48", description: "", variable: "enps_tug_detractor_bg", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_tug_passive_bg", value: "#94A3B8", description: "", variable: "enps_tug_passive_bg", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_tug_promoter_bg", value: "#0D9488", description: "", variable: "enps_tug_promoter_bg", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_tug_text_on", value: "#FFFFFF", description: "", variable: "enps_tug_text_on", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_divider", value: "#F1F5F9", description: "", variable: "enps_divider", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_dist_axis", value: "#E2E8F0", description: "", variable: "enps_dist_axis", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_dist_label", value: "#64748B", description: "", variable: "enps_dist_label", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_det_text", value: "#E11D48", description: "", variable: "enps_det_text", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_pas_text", value: "#94A3B8", description: "", variable: "enps_pas_text", fundamental_color: "", heatmap_color: "" },
  { category: "eNPS", key: "enps_pro_text", value: "#0D9488", description: "", variable: "enps_pro_text", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_slide_bg", value: "#F8FAFC", description: "", variable: "heatmap_slide_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_title", value: "#0F172A", description: "", variable: "heatmap_title", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_subtitle", value: "#64748B", description: "", variable: "heatmap_subtitle", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_legend_text", value: "#64748B", description: "", variable: "heatmap_legend_text", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_legend_start", value: "#EB7161", description: "", variable: "heatmap_legend_start", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_legend_mid", value: "#F1F5F9", description: "", variable: "heatmap_legend_mid", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_legend_end", value: "#81BBC2", description: "", variable: "heatmap_legend_end", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_card_bg", value: "#FFFFFF", description: "", variable: "heatmap_card_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_card_border", value: "#E2E8F0", description: "", variable: "heatmap_card_border", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_card_shadow", value: "rgba(0,0,0,0.04)", description: "", variable: "heatmap_card_shadow", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_card_title", value: "#0F172A", description: "", variable: "heatmap_card_title", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_table_header_text", value: "#64748B", description: "", variable: "heatmap_table_header_text", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_table_header_border", value: "#E2E8F0", description: "", variable: "heatmap_table_header_border", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_row_label_text", value: "#334155", description: "", variable: "heatmap_row_label_text", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_row_border", value: "#F1F5F9", description: "", variable: "heatmap_row_border", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_pill_text", value: "#1E293B", description: "", variable: "heatmap_pill_text", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_pill_na_bg", value: "#F8FAFC", description: "", variable: "heatmap_pill_na_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_pill_na_text", value: "#94A3B8", description: "", variable: "heatmap_pill_na_text", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_pill_na_border", value: "#CBD5E1", description: "", variable: "heatmap_pill_na_border", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_pill_pos_strong", value: "#81BBC2", description: "", variable: "heatmap_pill_pos_strong", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_pill_pos_soft", value: "#D1E6E9", description: "", variable: "heatmap_pill_pos_soft", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_pill_neutral", value: "#F1F5F9", description: "", variable: "heatmap_pill_neutral", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_pill_neg_soft", value: "#FFD8D1", description: "", variable: "heatmap_pill_neg_soft", fundamental_color: "", heatmap_color: "" },
  { category: "Heatmap", key: "heatmap_pill_neg_strong", value: "#EB7161", description: "", variable: "heatmap_pill_neg_strong", fundamental_color: "", heatmap_color: "" },
  { category: "Item Distribution", key: "itemdist_slide_bg", value: "#F8FAFC", description: "", variable: "itemdist_slide_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Item Distribution", key: "itemdist_card_bg", value: "#FFFFFF", description: "", variable: "itemdist_card_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Item Distribution", key: "itemdist_card_border", value: "#E2E8F0", description: "", variable: "itemdist_card_border", fundamental_color: "", heatmap_color: "" },
  { category: "Item Distribution", key: "itemdist_card_shadow", value: "rgba(0,0,0,0.04)", description: "", variable: "itemdist_card_shadow", fundamental_color: "", heatmap_color: "" },
  { category: "Item Distribution", key: "itemdist_title", value: "#0F172A", description: "", variable: "itemdist_title", fundamental_color: "", heatmap_color: "" },
  { category: "Item Distribution", key: "itemdist_subtitle", value: "#64748B", description: "", variable: "itemdist_subtitle", fundamental_color: "", heatmap_color: "" },
  { category: "Item Distribution", key: "itemdist_legend_text", value: "#64748B", description: "", variable: "itemdist_legend_text", fundamental_color: "", heatmap_color: "" },
  { category: "Item Distribution", key: "itemdist_header_label", value: "#94A3B8", description: "", variable: "itemdist_header_label", fundamental_color: "", heatmap_color: "" },
  { category: "Item Distribution", key: "itemdist_row_label", value: "#334155", description: "", variable: "itemdist_row_label", fundamental_color: "", heatmap_color: "" },
  { category: "Item Distribution", key: "itemdist_row_border", value: "#F1F5F9", description: "", variable: "itemdist_row_border", fundamental_color: "", heatmap_color: "" },
  { category: "Item Distribution", key: "itemdist_mean_text", value: "#0F172A", description: "", variable: "itemdist_mean_text", fundamental_color: "", heatmap_color: "" },
  { category: "Item Distribution", key: "itemdist_stack_bg", value: "#F1F5F9", description: "", variable: "itemdist_stack_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_slide_bg", value: "#F8FAFC", description: "", variable: "model_slide_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_card_bg", value: "#FFFFFF", description: "", variable: "model_card_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_card_border", value: "#E2E8F0", description: "", variable: "model_card_border", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_card_shadow", value: "rgba(0,0,0,0.05)", description: "", variable: "model_card_shadow", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_header_accent", value: "#0F172A", description: "", variable: "model_header_accent", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_title", value: "#0F172A", description: "", variable: "model_title", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_subtitle", value: "#64748B", description: "", variable: "model_subtitle", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_section_title", value: "#0F172A", description: "", variable: "model_section_title", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_section_rule", value: "#F1F5F9", description: "", variable: "model_section_rule", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_metric_header", value: "#94A3B8", description: "", variable: "model_metric_header", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_label", value: "#334155", description: "", variable: "model_label", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_track_bg", value: "#E2E8F0", description: "", variable: "model_track_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_stem", value: "#CBD5E1", description: "", variable: "model_stem", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_line", value: "#94A3B8", description: "", variable: "model_line", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_line_baseline", value: "#334155", description: "", variable: "model_line_baseline", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_line_label", value: "#64748B", description: "", variable: "model_line_label", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_metric_raw", value: "#0F172A", description: "", variable: "model_metric_raw", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_delta_pos", value: "#15803D", description: "", variable: "model_delta_pos", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_delta_neg", value: "#EB7161", description: "", variable: "model_delta_neg", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_delta_neu", value: "#64748B", description: "", variable: "model_delta_neu", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_zone_ni", value: "#F59E0B", description: "", variable: "model_zone_ni", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_zone_is", value: "#16A34A", description: "", variable: "model_zone_is", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_zone_as", value: "#059669", description: "", variable: "model_zone_as", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_zone_il", value: "#0D9488", description: "", variable: "model_zone_il", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_point_ni", value: "#D97706", description: "", variable: "model_point_ni", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_point_is", value: "#15803D", description: "", variable: "model_point_is", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_point_as", value: "#047857", description: "", variable: "model_point_as", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_point_il", value: "#0F766E", description: "", variable: "model_point_il", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_point_border", value: "#FFFFFF", description: "", variable: "model_point_border", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_point_ghost_bg", value: "#FFFFFF", description: "", variable: "model_point_ghost_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_point_ghost_border", value: "#94A3B8", description: "", variable: "model_point_ghost_border", fundamental_color: "", heatmap_color: "" },
  { category: "Model Representation", key: "model_legend_text_on", value: "#FFFFFF", description: "", variable: "model_legend_text_on", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_page_bg", value: "#F8FAFC", description: "", variable: "demo_page_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_grid_gap", value: "#E2E8F0", description: "", variable: "demo_grid_gap", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_panel_bg", value: "#FFFFFF", description: "", variable: "demo_panel_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_panel_border", value: "#E2E8F0", description: "", variable: "demo_panel_border", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_panel_shadow", value: "rgba(15,23,42,0.04)", description: "", variable: "demo_panel_shadow", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_title", value: "#0F172A", description: "", variable: "demo_title", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_subtitle", value: "#64748B", description: "", variable: "demo_subtitle", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_panel_title", value: "#0F172A", description: "", variable: "demo_panel_title", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_panel_subtitle", value: "#64748B", description: "", variable: "demo_panel_subtitle", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_empty_text", value: "#94A3B8", description: "", variable: "demo_empty_text", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_bi_axis_mid", value: "#334155", description: "", variable: "demo_bi_axis_mid", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_bi_axis_label", value: "#94A3B8", description: "", variable: "demo_bi_axis_label", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_bi_side_label_left", value: "#0EA5E9", description: "", variable: "demo_bi_side_label_left", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_bi_side_label_right", value: "#0F766E", description: "", variable: "demo_bi_side_label_right", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_bi_side_count", value: "#64748B", description: "", variable: "demo_bi_side_count", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_bi_bar_left_bg", value: "#0EA5E9", description: "", variable: "demo_bi_bar_left_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_bi_bar_right_bg", value: "#0F766E", description: "", variable: "demo_bi_bar_right_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_bi_bar_text", value: "#FFFFFF", description: "", variable: "demo_bi_bar_text", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_cb_label", value: "#334155", description: "", variable: "demo_cb_label", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_cb_track_bg", value: "#F1F5F9", description: "", variable: "demo_cb_track_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_cb_value_text", value: "#FFFFFF", description: "", variable: "demo_cb_value_text", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_cb_bar_1", value: "#0F766E", description: "", variable: "demo_cb_bar_1", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_cb_bar_2", value: "#0EA5E9", description: "", variable: "demo_cb_bar_2", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_cb_bar_3", value: "#14B8A6", description: "", variable: "demo_cb_bar_3", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_cb_bar_4", value: "#F59E0B", description: "", variable: "demo_cb_bar_4", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_cb_bar_5", value: "#F97316", description: "", variable: "demo_cb_bar_5", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_cb_bar_6", value: "#64748B", description: "", variable: "demo_cb_bar_6", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ct_text_on", value: "#FFFFFF", description: "", variable: "demo_ct_text_on", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ct_border", value: "rgba(255,255,255,0.28)", description: "", variable: "demo_ct_border", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ct_tile_1", value: "#0F766E", description: "", variable: "demo_ct_tile_1", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ct_tile_2", value: "#0EA5E9", description: "", variable: "demo_ct_tile_2", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ct_tile_3", value: "#14B8A6", description: "", variable: "demo_ct_tile_3", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ct_tile_4", value: "#F59E0B", description: "", variable: "demo_ct_tile_4", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ct_tile_5", value: "#F97316", description: "", variable: "demo_ct_tile_5", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ct_tile_6", value: "#64748B", description: "", variable: "demo_ct_tile_6", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ob_axis_label", value: "#64748B", description: "", variable: "demo_ob_axis_label", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ob_callout_bg", value: "#FFFFFF", description: "", variable: "demo_ob_callout_bg", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ob_callout_text", value: "#0F172A", description: "", variable: "demo_ob_callout_text", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ob_callout_line", value: "#94A3B8", description: "", variable: "demo_ob_callout_line", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ob_seg_1", value: "#99F6E4", description: "", variable: "demo_ob_seg_1", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ob_seg_2", value: "#5EEAD4", description: "", variable: "demo_ob_seg_2", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ob_seg_3", value: "#2DD4BF", description: "", variable: "demo_ob_seg_3", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ob_seg_4", value: "#0D9488", description: "", variable: "demo_ob_seg_4", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ob_seg_5", value: "#0F766E", description: "", variable: "demo_ob_seg_5", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ob_seg_text_dark", value: "#0F766E", description: "", variable: "demo_ob_seg_text_dark", fundamental_color: "", heatmap_color: "" },
  { category: "Demographics", key: "demo_ob_seg_text_light", value: "#FFFFFF", description: "", variable: "demo_ob_seg_text_light", fundamental_color: "", heatmap_color: "" }
];

